- name: Install MYSQL
  package:
    name: mariadb-server 
    state: present
- name: Install the Python MySQL Support Libraries
  package: 
    name: MySQL-python 
    state: latest
  tags: ['never']
- name: start mysql server and enable it on reboot
  service: 
    name: mariadb 
    state: started 
    enabled: true 
- debug: msg="{{ ansible_hostname }}"
- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
