- name: Install Tomcat packages 
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - tomcat
    - tomcat-docs-webapp
    - tomcat-javadoc
    - tomcat-webapps
    - tomcat-admin-webapps 
    - firewalld
    - unzip
#  tags: ['never']
- name: ensure tomcat is running
  service:
    name: tomcat
    state: started
  become: true
- name: Open port 8080 
  firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
  become: true
- name: Open AJP port 8009
  firewalld:
    port: 8009/tcp
    permanent: yes
    state: enabled
  become: true
  register: fwstat
- name: Restart the firewalld service to load in the firewall changes
  service: 
    name: firewalld 
    state: restarted
  become: true
  when: fwstat.changed
- name: Create directory
  file:
    path: /opt/opencms
    owner: tomcat
    group: tomcat
    state: directory
    mode: 0755
- name: Get opencms source package
  get_url: 
    url: http://www.opencms.org/downloads/opencms/opencms-10.5.4.zip
    dest: /opt/opencms/
- name: Unzip source
  shell: cd /opt/opencms; unzip -o /opt/opencms/opencms-10.5.4.zip
- name: Deploy opencms war in tomcat
  copy:
    src: /opt/opencms/opencms.war
    dest: /var/lib/tomcat/webapps/ROOT.war
    owner: tomcat
    group: tomcat
    mode: 0755
    remote_src: yes
- name: Create AJP connector
  lineinfile: 
    dest: /usr/share/tomcat/conf/server.xml
    regexp: '^(.*)<Connector port="8009"(.*)$' 
    line: '<Connector port="8009" enableLookups="false" redirectPort="8443" protocol="AJP/1.3" />'
    backrefs: yes
- name: Setup config file
  shell: |
    echo "setup.webapp.path=/var/lib/tomcat/webapps/ROOT
    setup.default.webapp=ROOT
    setup.install.components=workplace,releasenotes,template3,devdemo,bootstrap

    db.product=mysql
    db.provider=mysql
    db.create.user=root
    db.create.pwd={{ mysql_root_password }}
    db.worker.user=root
    db.worker.pwd={{ mysql_root_password }}
    db.connection.url=jdbc:mysql://{{ db_node_ip }}:3306/
    db.name=db_opencms
    db.create.db=true
    db.create.tables=true
    db.dropDb=true
    db.default.tablespace=
    db.index.tablespace=
    db.jdbc.driver=org.gjt.mm.mysql.Driver
    db.template.db=
    db.temporary.tablespace=

    server.url=http://{{ web_node_ip }}
    server.name={{ web_node_ip }}
    server.ethernet.address=
    server.servlet.mapping=" > /opt/opencms/config
- file:
    path: /opt/opencms/config
    owner: tomcat
    group: tomcat
    mode: 0744
- name: Perform opemcms Installation
  shell: cd /opt/opencms/; java -classpath "/var/lib/tomcat/webapps/ROOT/WEB-INF/lib/*:/var/lib/tomcat/webapps/ROOT/WEB-INF/classes:/usr/share/tomcat/lib/*" org.opencms.setup.CmsAutoSetup -path /opt/opencms/config
