- name: Install apache packages 
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - firewalld
  become: true
#- name: Install semanage utility to enable custom directory logs
#  package:
#    name: policycoreutils-python
#    state: present
- name: ensure httpd is running
  service:
    name: httpd 
    state: started
  become: true
- name: Open port 80 for http access
  firewalld:
    service: http
    permanent: true
    state: enabled
  become: true
  register: fwstat
- name: Restart the firewalld service to load in the firewall changes
  service: 
    name: firewalld 
    state: restarted
  become: true
  when: fwstat.changed
#- name: SELinux relabel
#  shell: semanage fcontext -a -t httpd_log_t "/var/www(/.*)?"; restorecon -Rv /var/www
#  become: true
- name: Create folders and Permissions for vhost
  shell: |
    mkdir -p /var/www/devopstest.com/public_html
    chown -R apache.apache /var/www/devopstest.com/public_html   
    chmod -R 755 /var/www
    mkdir -p /etc/httpd/sites-available
    mkdir -p /etc/httpd/sites-enabled
  become: true
- name: Enable custom sites suppport
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: IncludeOptional sites-enabled/*.conf  
  become: true
- name: Create domain vhost file
  shell: |
    echo "<VirtualHost *:80>

    ServerAdmin webmaster@"{{ domain_name }}"
    ServerName www."{{ domain_name }}"
    ServerAlias "{{ domain_name }}"

    RewriteEngine On
    LogLevel mod_rewrite.c:trace1

    ProxyPass         / ajp://"{{ app_node_ip }}":8009/
    ProxyPassReverse  / http://"{{ domain_name }}"/
    # Connect to Tomcat using proxy_ajp
    ProxyPreserveHost On
    ProxyPass /opencms ajp://"{{ app_node_ip }}":8009/opencms
    ProxyPass /webdav(.*) ajp://"{{ app_node_ip }}":8009/webdav$1
    ProxyPass /VAADIN ajp://"{{ app_node_ip }}":8009/VAADIN
    ProxyPass /workplace ajp://"{{ app_node_ip }}":8009/workplace
    </VirtualHost>" > /etc/httpd/sites-available/"{{ domain_name }}".conf
  become: true 
- name: Create site link and enable
  file:
    src: /etc/httpd/sites-available/{{ domain_name }}.conf
    dest: /etc/httpd/sites-enabled/{{ domain_name }}.conf
    owner: apache
    group: apache
    state: link
  become: true
- name: Restart apache
  service:
    name: httpd
    state: restarted
  become: true

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2
